"""Remove degree column from students

Revision ID: 32c4ee6e578b
Revises: abf1d84d8bce
Create Date: 2025-05-12 17:39:46.683156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32c4ee6e578b'
down_revision: Union[str, None] = 'abf1d84d8bce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'degree')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('degree', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
