"""tables

Revision ID: 5a3fb40af458
Revises: d13b188c69b2
Create Date: 2025-05-07 22:51:59.953120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a3fb40af458'
down_revision: Union[str, None] = 'd13b188c69b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.add_column('students', sa.Column('board', sa.String(length=100), nullable=True))
    op.add_column('students', sa.Column('twelfth_mark', sa.Integer(), nullable=True))
    op.add_column('students', sa.Column('engineering_cutoff', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'engineering_cutoff')
    op.drop_column('students', 'twelfth_mark')
    op.drop_column('students', 'board')
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(), nullable=False),
    sa.Column('is_admin', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###
