"""Added new columns to students table

Revision ID: 6781e1659423
Revises: 147cfabc7964
Create Date: 2025-05-12 18:06:59.950229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6781e1659423'
down_revision: Union[str, None] = '147cfabc7964'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommenders', sa.Column('offcode', sa.String(), nullable=True))
    op.add_column('recommenders', sa.Column('percode', sa.String(), nullable=True))
    op.add_column('students', sa.Column('stdcode', sa.String(), nullable=True))
    op.add_column('students', sa.Column('degree', sa.String(), nullable=True))
    op.add_column('students', sa.Column('maths', sa.Float(), nullable=True))
    op.add_column('students', sa.Column('physics', sa.Float(), nullable=True))
    op.add_column('students', sa.Column('chemistry', sa.Float(), nullable=True))
    op.add_column('students', sa.Column('nata', sa.Float(), nullable=True))
    op.add_column('students', sa.Column('studybreak', sa.Integer(), nullable=True))
    op.add_column('students', sa.Column('msc_cutoff', sa.Float(), nullable=True))
    op.add_column('students', sa.Column('barch_cutoff', sa.Float(), nullable=True))
    op.add_column('students', sa.Column('bdes_cutoff', sa.Float(), nullable=True))
    op.add_column('students', sa.Column('applicationstatus', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'applicationstatus')
    op.drop_column('students', 'bdes_cutoff')
    op.drop_column('students', 'barch_cutoff')
    op.drop_column('students', 'msc_cutoff')
    op.drop_column('students', 'studybreak')
    op.drop_column('students', 'nata')
    op.drop_column('students', 'chemistry')
    op.drop_column('students', 'physics')
    op.drop_column('students', 'maths')
    op.drop_column('students', 'degree')
    op.drop_column('students', 'stdcode')
    op.drop_column('recommenders', 'percode')
    op.drop_column('recommenders', 'offcode')
    # ### end Alembic commands ###
