"""added application number

Revision ID: 738aa138b265
Revises: ce06b7fcb9cf
Create Date: 2025-05-09 12:41:23.803348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '738aa138b265'
down_revision: Union[str, None] = 'ce06b7fcb9cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('application_number', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'students', ['application_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='unique')
    op.drop_column('students', 'application_number')
    # ### end Alembic commands ###
