"""added 12th mark

Revision ID: 8534cadbc670
Revises: 0691a3840076
Create Date: 2025-05-08 00:18:22.108840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8534cadbc670'
down_revision: Union[str, None] = '0691a3840076'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('board', sa.String(length=100), nullable=True))
    op.add_column('students', sa.Column('twelfth_mark', sa.Integer(), nullable=True))
    op.add_column('students', sa.Column('engineering_cutoff', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'engineering_cutoff')
    op.drop_column('students', 'twelfth_mark')
    op.drop_column('students', 'board')
    # ### end Alembic commands ###
