"""add year_of_admission

Revision ID: a5e4cc1cdaa0
Revises: 6154fcc58022
Create Date: 2026-03-22 11:12:27.200142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5e4cc1cdaa0'
down_revision: Union[str, None] = '6154fcc58022'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('admission_outcomes', sa.Column('year_of_admission', sa.String(), nullable=True))
    # op.add_column('admission_outcomes', sa.Column('category', sa.String(), nullable=True))
    # op.alter_column('admission_outcomes', 'course_type',
    #            existing_type=sa.VARCHAR(),
    #            nullable=True)
    op.add_column('students', sa.Column('year_of_admission', sa.String(), nullable=True))
    op.add_column('users', sa.Column('token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token')
    op.drop_column('students', 'year_of_admission')
    # op.alter_column('admission_outcomes', 'course_type',
    #            existing_type=sa.VARCHAR(),
    #            nullable=False)
    # op.drop_column('admission_outcomes', 'category')
    # op.drop_column('admission_outcomes', 'year_of_admission')
    # ### end Alembic commands ###
