"""Add users table

Revision ID: b74794113bdd
Revises: 5a3fb40af458
Create Date: 2025-05-07 23:20:50.821321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b74794113bdd'
down_revision: Union[str, None] = '5a3fb40af458'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'board')
    op.drop_column('students', 'twelfth_mark')
    op.drop_column('students', 'engineering_cutoff')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('engineering_cutoff', sa.FLOAT(), nullable=True))
    op.add_column('students', sa.Column('twelfth_mark', sa.INTEGER(), nullable=True))
    op.add_column('students', sa.Column('board', sa.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
