"""added fiels

Revision ID: ce06b7fcb9cf
Revises: 1c22a71387df
Create Date: 2025-05-08 11:12:33.950355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce06b7fcb9cf'
down_revision: Union[str, None] = '1c22a71387df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('college', sa.String(), nullable=True))
    op.add_column('students', sa.Column('markpercentage', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'markpercentage')
    op.drop_column('students', 'college')
    # ### end Alembic commands ###
