"""Add users table

Revision ID: d13b188c69b2
Revises: 1c9b09e62509
Create Date: 2025-05-07 15:59:50.855978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd13b188c69b2'
down_revision: Union[str, None] = '1c9b09e62509'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('school', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('aadhar_number', sa.String(), nullable=True),
    sa.Column('parent_annual_income', sa.DECIMAL(), nullable=True),
    sa.Column('community', sa.String(), nullable=True),
    sa.Column('branch_1', sa.String(), nullable=True),
    sa.Column('branch_2', sa.String(), nullable=True),
    sa.Column('branch_3', sa.String(), nullable=True),
    sa.Column('date_of_application', sa.Date(), nullable=True),
    sa.Column('year_of_passing', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aadhar_number')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('admission_outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommenders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('designation', sa.String(), nullable=True),
    sa.Column('affiliation', sa.String(), nullable=True),
    sa.Column('office_address', sa.String(), nullable=True),
    sa.Column('office_phone_number', sa.String(), nullable=True),
    sa.Column('personal_phone_number', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommenders')
    op.drop_table('admission_outcomes')
    op.drop_table('users')
    op.drop_table('students')
    # ### end Alembic commands ###
