"""Added stdcode and updated students and recommenders tables

Revision ID: 4b1a7937d14c
Revises: 
Create Date: 2025-05-12 18:27:52.557404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b1a7937d14c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommenders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('offcode', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('percode', sa.String(), nullable=True))

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stdcode', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('degree', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('maths', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('physics', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('chemistry', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('nata', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('studybreak', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('msc_cutoff', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('barch_cutoff', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('bdes_cutoff', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('applicationstatus', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('applicationstatus')
        batch_op.drop_column('bdes_cutoff')
        batch_op.drop_column('barch_cutoff')
        batch_op.drop_column('msc_cutoff')
        batch_op.drop_column('studybreak')
        batch_op.drop_column('nata')
        batch_op.drop_column('chemistry')
        batch_op.drop_column('physics')
        batch_op.drop_column('maths')
        batch_op.drop_column('degree')
        batch_op.drop_column('stdcode')

    with op.batch_alter_table('recommenders', schema=None) as batch_op:
        batch_op.drop_column('percode')
        batch_op.drop_column('offcode')

    # ### end Alembic commands ###
